export const catalogAgents = [
  [1,"inbox-action-router","Inbox Action Router","Operations","Classify actionable email and prepare Linear tasks and Slack updates.",["gmail","linear","slack"],["Productivity","Production"],"0 8 * * 1-5"],
  [1,"meeting-follow-up-chief","Meeting Follow-up Chief","Operations","Turn meeting records into decisions, Notion notes, and follow-up email drafts.",["fathom","notion","gmail"],["Productivity","Production"],"0 17 * * 1-5"],
  [1,"support-escalation-manager","Support Escalation Manager","Support","Identify urgent support cases and prepare engineering escalations and team alerts.",["intercom","linear","slack"],["Production","Productivity"],"0 */4 * * *"],
  [1,"voice-of-customer-analyst","Voice of Customer Analyst","Product","Cluster customer feedback into evidence-linked themes and a reviewable insight report.",["intercom","gorgias","notion"],["Research","Productivity"],"0 9 * * 1"],
  [1,"github-issue-commander","GitHub Issue Commander","Engineering","Deduplicate and prioritize GitHub issues, then prepare Linear work and a team digest.",["github","linear","slack"],["Engineering","Productivity"],"0 9 * * 1-5"],
  [1,"release-communications-agent","Release Communications Agent","Engineering","Turn merged work into release notes and channel-specific announcement drafts.",["github","notion","slack"],["Engineering","Marketing"],"0 15 * * 5"],
  [1,"incident-scribe","Incident Scribe","Engineering","Build an evidence-backed incident timeline and draft updates and a postmortem.",["sentry","pagerduty","notion"],["Engineering","Production"],"0 */2 * * *"],
  [1,"lead-research-copilot","Lead Research Copilot","Sales","Research selected leads, enrich their context, and draft grounded outreach.",["hubspot","attio","gmail"],["Sales","Research"],"0 8 * * 1-5"],
  [1,"pipeline-hygiene-agent","Pipeline Hygiene Agent","Sales","Find stale or incomplete opportunities and prepare a correction queue.",["hubspot","salesforce"],["Sales","Productivity"],"0 7 * * 1"],
  [1,"content-repurposing-studio","Content Repurposing Studio","Marketing","Transform source content into reviewable channel-specific campaign drafts.",["googledocs","notion","linkedin"],["Marketing","Productivity"],"0 10 * * 1"],
  [1,"marketing-performance-analyst","Marketing Performance Analyst","Marketing","Explain acquisition changes and prepare a concise performance report.",["google_analytics","google_search_console","googlesheets"],["Marketing","Research"],"0 8 * * 1"],
  [1,"finance-close-assistant","Finance Close Assistant","Finance","Reconcile finance summaries, surface anomalies, and prepare a close pack.",["stripe","quickbooks","googlesheets"],["FinOps","Productivity"],"0 9 1 * *"],
  [1,"subscription-revenue-watcher","Subscription Revenue Watcher","Finance","Detect churn, failed-payment, and recurring-revenue patterns and propose actions.",["stripe"],["FinOps","Sales"],"0 8 * * 1"],
  [1,"hiring-review-assistant","Hiring Review Assistant","People","Apply a consistent hiring rubric and prepare evidence-based interview packets.",["greenhouse","googledocs","slack"],["Productivity","Research"],"0 8 * * 1-5"],
  [1,"executive-daily-brief","Executive Daily Brief","Leadership","Synthesize inbox, calendar, team, and project signals into a prioritized daily brief.",["gmail","googlecalendar","slack"],["Productivity","Research"],"0 7 * * 1-5"],
  [2,"renewal-risk-monitor","Renewal Risk Monitor","Customer Success","Review upcoming renewals and explain evidence-backed account risks.",["salesforce","hubspot"],["Sales","Research"],"0 8 * * 1"],
  [2,"sales-call-coach","Sales Call Coach","Sales","Extract objections and coaching opportunities from sales calls and preview CRM updates.",["gong","fathom","hubspot"],["Sales","Productivity"],"0 17 * * 5"],
  [2,"rfp-response-builder","RFP Response Builder","Sales","Build reviewable RFP response packages from source files and approved prior answers.",["googledrive","box","googledocs"],["Sales","Productivity"],"0 9 * * 1"],
  [2,"crm-deduplication-planner","CRM Deduplication Planner","Sales","Find likely duplicate contacts and companies and propose safe merge plans.",["hubspot","attio"],["Sales","Productivity"],"0 6 * * 0"],
  [2,"account-handoff-agent","Account Handoff Agent","Customer Success","Prepare structured sales-to-success handoffs with risks, promises, and next steps.",["hubspot","notion","slack"],["Sales","Productivity"],"0 16 * * 1-5"],
  [2,"customer-health-reporter","Customer Health Reporter","Customer Success","Summarize support and CRM signals into a weekly customer-health report.",["intercom","salesforce","notion"],["Sales","Research"],"0 8 * * 1"],
  [2,"support-knowledge-curator","Support Knowledge Curator","Support","Find repeated support answers and draft evidence-linked documentation improvements.",["zendesk","intercom","notion"],["Production","Research"],"0 9 * * 1"],
  [2,"review-response-desk","Review Response Desk","Support","Draft policy-aware responses to public feedback without posting them.",["facebook","instagram"],["Marketing","Sales"],"0 10 * * 1-5"],
  [2,"campaign-launch-coordinator","Campaign Launch Coordinator","Marketing","Check campaign readiness and prepare launch communications and remediation tasks.",["asana","slack","mailchimp"],["Marketing","Productivity"],"0 8 * * 1-5"],
  [2,"seo-opportunity-scout","SEO Opportunity Scout","Marketing","Turn search and traffic evidence into prioritized content briefs.",["google_search_console","google_analytics","googledocs"],["Marketing","Research"],"0 8 * * 1"],
  [2,"newsletter-editor","Newsletter Editor","Marketing","Assemble source material into a validated newsletter draft.",["googledocs","notion","mailchimp"],["Marketing","Productivity"],"0 9 * * 2"],
  [2,"social-listening-brief","Social Listening Brief","Marketing","Find timely Reddit and X conversations and summarize themes, risks, and opportunities.",["reddit"],["Marketing","Research"],"0 */4 * * *"],
  [2,"creator-sponsorship-manager","Creator Sponsorship Manager","Marketing","Extract sponsorship offers, compare terms, and prepare reply drafts.",["gmail","googlesheets"],["Marketing","Sales"],"0 9 * * 1-5"],
  [2,"event-follow-up-agent","Event Follow-up Agent","Marketing","Segment event attendees and prepare relevant follow-up campaigns.",["eventbrite","hubspot","gmail"],["Marketing","Sales"],"0 10 * * 1"],
  [2,"partner-update-composer","Partner Update Composer","Partnerships","Prepare recurring partner updates from CRM facts and approved workspace notes.",["hubspot","notion"],["Sales","Productivity"],"0 9 * * 5"],
  [3,"pull-request-risk-reviewer","Pull Request Risk Reviewer","Engineering","Analyze pull requests and produce a focused risk and rollout checklist.",["github","gitlab"],["Engineering","Production"],"0 9 * * 1-5"],
  [3,"dependency-update-planner","Dependency Update Planner","Engineering","Assess dependency changes in a sandbox and draft safe upgrade work.",["github"],["Engineering","Research"],"0 8 * * 1"],
  [3,"bug-reproduction-assistant","Bug Reproduction Assistant","Engineering","Turn issue reports and uploaded evidence into reproducible sandbox findings.",["github","linear"],["Engineering","Production"],"0 9 * * 1"],
  [3,"on-call-handoff-agent","On-call Handoff Agent","Engineering","Prepare concise handoffs from active incidents, alerts, and unresolved risks.",["pagerduty","sentry","slack"],["Engineering","Production"],"0 6,18 * * *"],
  [3,"engineering-weekly-digest","Engineering Weekly Digest","Engineering","Summarize shipped work, blockers, and upcoming engineering risks.",["github","linear","slack"],["Engineering","Productivity"],"0 15 * * 5"],
  [3,"product-feedback-synthesizer","Product Feedback Synthesizer","Product","Cluster product feedback into evidence-linked opportunities.",["productboard","intercom","notion"],["Research","Productivity"],"0 8 * * 1"],
  [3,"roadmap-consistency-checker","Roadmap Consistency Checker","Product","Find contradictory roadmap status, ownership, and dates across planning systems.",["productboard","linear","notion"],["Productivity","Research"],"0 8 * * 1"],
  [3,"spec-to-task-planner","Spec-to-Task Planner","Product","Convert approved specifications into reviewable implementation task drafts.",["notion","confluence","linear"],["Productivity","Engineering"],"0 9 * * 1"],
  [3,"design-handoff-auditor","Design Handoff Auditor","Design","Detect missing states, assets, and acceptance criteria before implementation.",["figma","zeplin","linear"],["Production","Engineering"],"0 9 * * 1-5"],
  [3,"research-repository-curator","Research Repository Curator","Research","Normalize research artifacts and prepare an evidence-linked insight index.",["googledrive","notion","miro"],["Research","Productivity"],"0 8 * * 1"],
  [3,"async-standup-manager","Async Standup Manager","Operations","Collect team updates and prepare a concise blocker-aware digest.",["slack","microsoft_teams","linear"],["Productivity","Production"],"0 9 * * 1-5"],
  [3,"meeting-load-optimizer","Meeting Load Optimizer","Operations","Analyze recurring meetings and recommend consolidation or cancellation.",["googlecalendar"],["Productivity","Research"],"0 8 * * 1"],
  [3,"project-risk-radar","Project Risk Radar","Operations","Detect overdue dependencies and prepare evidence-based escalation drafts.",["asana","clickup","monday"],["Productivity","Production"],"0 8 * * 1-5"],
  [3,"knowledge-base-gardener","Knowledge Base Gardener","Operations","Find stale, duplicated, and orphaned knowledge pages and propose cleanup.",["notion","confluence"],["Productivity","Research"],"0 8 * * 1"],
  [3,"okr-progress-narrator","OKR Progress Narrator","Leadership","Produce an evidence-backed weekly OKR progress narrative.",["googlesheets","notion","linear"],["Productivity","Research"],"0 8 * * 1"],
  [4,"expense-policy-reviewer","Expense Policy Reviewer","Finance","Classify receipts and flag policy exceptions for human review.",["gmail","googledrive","quickbooks"],["FinOps","Productivity"],"0 8 * * 1"],
  [4,"cash-flow-briefing-agent","Cash-flow Briefing Agent","Finance","Explain weekly cash movements, anomalies, and near-term risks.",["stripe","quickbooks"],["FinOps","Research"],"0 8 * * 1"],
  [4,"contract-obligation-tracker","Contract Obligation Tracker","Legal Operations","Extract obligations and dates into a reviewable contract register.",["box","googledrive","notion"],["Productivity","Research"],"0 8 * * 1"],
  [4,"sheets-to-database-steward","Sheets-to-Database Steward","Data","Validate spreadsheet rows and preview database upserts before approval.",["googlesheets","supabase"],["Production","Engineering"],"0 6 * * *"],
  [4,"cross-system-data-auditor","Cross-System Data Auditor","Data","Detect cross-system drift and generate a reconciliation plan without mutating records.",["googlesheets","hubspot","asana"],["Production","Research"],"0 7 * * 1"],
].map(([wave,slug,name,department,description,connections,labels,cron]) => ({
  wave, slug, name, department, description, connections, labels, cron,
  trigger: "chat + scheduled polling",
  setupEffort: connections.length === 1 ? "low" : connections.length === 2 ? "medium" : "guided",
  autonomy: "read, analyze, and draft; confirm before consequential writes",
  primitives: ["Connections","schedules","skills","scripts","hooks","memory","outbound files"],
}));
