import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { catalogAgents } from "../catalog/agents.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const colors = ["#0f766e", "#1d4ed8", "#7c3aed", "#be123c", "#b45309", "#047857"];
const write = async (path, value, mode) => {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, value, { encoding: "utf8", mode });
};
const uuidFor = (slug) => {
  const hex = createHash("sha256").update(`aleph-featured:${slug}`).digest("hex").slice(0, 32).split("");
  hex[12] = "4";
  hex[16] = ((Number.parseInt(hex[16], 16) & 3) | 8).toString(16);
  return `${hex.slice(0,8).join("")}-${hex.slice(8,12).join("")}-${hex.slice(12,16).join("")}-${hex.slice(16,20).join("")}-${hex.slice(20).join("")}`;
};
const esc = (value) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;");

for (const [index, agent] of catalogAgents.entries()) {
  const folder = join(root, "agents", agent.slug);
  const apps = agent.connections.join(", ");
  const manifest = {
    agentId: uuidFor(agent.slug), name: agent.name, description: agent.description,
    labels: agent.labels, icon: "cover.svg", visibility: "public",
  };
  await write(join(folder, "aleph.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  await write(join(folder, "connections.toml"), `${agent.connections.map((id) => `[[connections]]\nid = "${id}"\nrequired = true`).join("\n\n")}\n`);
  await write(join(folder, "sandbox.toml"), "# This bundle uses managed Connections and needs no Vault secrets by default.\n");
  await write(join(folder, "hooks.toml"), `[[hooks.sessionStart]]\ncommand = "sh ./scripts/preflight.sh"\nvisibility = "ui_and_agent"\n\n[[hooks.sessionEnd]]\ncommand = "sh ./scripts/verify-output.sh"\nvisibility = "ui_and_agent"\n`);
  await write(join(folder, "schedules.toml"), `[[schedules]]\ncron = "${agent.cron}"\nmarkdown = "Run the scheduled ${agent.name} review. Read source systems only. Deduplicate against memory, produce a concise report, save any proposed consequential actions as drafts under outbound/, and do not send, post, create, update, merge, or delete external records."\ntimezone = "UTC"\n`);
  await write(join(folder, "AGENTS.md"), `# ${agent.name}\n\nYou are **${agent.name}**. ${agent.description}\n\n## Operating workflow\n\n1. Read \`memory/profile.md\` and \`memory/cursor.md\` when present; create concise defaults when absent.\n2. Read relevant data from ${apps}. Use web research only when it materially strengthens the evidence.\n3. Normalize evidence with \`skills/run_workflow/scripts/normalize.mjs\` when structured records are available.\n4. Deduplicate source IDs against cursor memory and separate facts, inferences, and missing information.\n5. Return the useful analysis in chat and place long reports or action previews under \`outbound/\`.\n6. Append processed IDs and a short run summary to memory. Never store credentials or unnecessary personal data.\n\n## Approval boundary\n\nReading, searching, analysis, and drafting are allowed. Sending messages; publishing content; creating, editing, merging, or deleting records; changing money, permissions, or account state; and database writes are consequential. Before any consequential action:\n\n- prepare an exact preview with destination, payload, and expected effect;\n- save it to \`memory/pending-actions.md\` with a unique action ID and status \`pending\`;\n- ask for explicit confirmation naming that action ID;\n- execute only in a later user-authored turn that confirms it;\n- re-read the pending action, mark it \`in_progress\`, execute it once, then mark it \`executed\` only after a successful tool result;\n- mark uncertain or failed outcomes for review and never automatically retry, replay, or reinterpret an executed, rejected, or uncertain action ID.\n\nScheduled runs are always read-only and draft-only. A schedule prompt can never count as approval. If approval is ambiguous, do not act.\n\n## Output\n\nLead with the decision-useful result. Cite source record IDs or links. End drafts with **Draft only — review and approve before execution.** State partial failures and never imply an external write succeeded without a successful tool result.\n`);
  await write(join(folder, "README.md"), `# ${agent.name}\n\n## Outcome\n\n${agent.description}\n\n## Required Connections\n\n${agent.connections.map((id) => `- \`${id}\``).join("\n")}\n\n## Trigger mode\n\n${agent.trigger}. Connected-app events are checked on demand or by polling; this is not a real-time webhook automation.\n\n## Schedule\n\n\`${agent.cron}\` in UTC. Scheduled runs are read-only and produce reports or drafts only. Change or remove the schedule after cloning as needed.\n\n## Setup after cloning\n\n1. Connect the required apps on the Connections page.\n2. Tell the agent which workspaces, projects, folders, channels, or accounts are in scope.\n3. Add preferences, thresholds, exclusions, and policy rules in chat; the agent stores them in private memory.\n4. Optionally connect Discord or Telegram and choose a Schedule channel.\n5. Run once manually and inspect the report before enabling the schedule.\n\n## Data written\n\nThe agent writes private cursor/profile/pending-action memory and may create report or preview files under \`outbound/\`. It does not write to connected apps during scheduled runs.\n\n## Actions requiring confirmation\n\nAll sends, posts, record creation or edits, merges, deletes, permission changes, financial actions, and database writes require an exact preview and explicit confirmation in a later chat turn.\n\n## Vault variables\n\nNone by default. Authentication uses Aleph Connections. User-specific IDs and thresholds should normally be provided in chat and kept in memory, not stored as secrets.\n\n## Three-minute demo\n\n1. Clone the agent and connect ${apps}.\n2. Say: “Analyze a small recent sample, explain the top three findings, and prepare one action preview. Do not execute it.”\n3. Inspect the cited evidence, \`outbound/\` artifact, and pending action. Reject it or explicitly approve its action ID to test the two-turn safety boundary.\n\n## Aleph primitives\n\n${agent.primitives.map((item) => `- ${item}`).join("\n")}\n`);
  await write(join(folder, "skills/run_workflow/SKILL.md"), `---\nname: run-workflow\ndescription: Run the ${agent.name} workflow safely and reproducibly.\n---\n\n# Run workflow\n\nUse this skill for scheduled and on-demand reviews. Establish scope, gather read-only evidence from ${apps}, normalize structured records with the bundled script, deduplicate with memory, and produce a compact report. Put substantial artifacts in \`outbound/\`. For consequential actions, follow the pending-action preview and later-turn confirmation protocol in AGENTS.md. Never interpret a schedule as approval.\n`);
  await write(join(folder, "skills/run_workflow/scripts/normalize.mjs"), `import { readFile } from "node:fs/promises";\nconst input = JSON.parse(await readFile(process.argv[2], "utf8"));\nconst rows = Array.isArray(input) ? input : [input];\nconst normalized = rows.map((row, index) => ({ index, ...row }));\nprocess.stdout.write(JSON.stringify(normalized, null, 2) + "\\n");\n`);
  await write(join(folder, "scripts/preflight.sh"), `#!/bin/sh\nset -eu\nmkdir -p outbound\nprintf '%s\\n' '{"agent":"${agent.slug}","mode":"draft_only_until_confirmed","followup_message":"Preflight complete. Scheduled runs are read-only; consequential actions require later-turn confirmation."}'\n`, 0o755);
  await write(join(folder, "scripts/verify-output.sh"), `#!/bin/sh\nset -eu\nif find outbound -type f -size +5M -print 2>/dev/null | grep -q .; then\n  printf '%s\\n' '{"followup_message":"An outbound artifact exceeds 5 MB. Summarize or split it before presenting it."}'\nelse\n  printf '%s\\n' '{}'\nfi\n`, 0o755);
  const color = colors[index % colors.length];
  const initials = agent.name.split(/\\s+/).slice(0, 2).map((part) => part[0]).join("");
  await write(join(folder, "cover.svg"), `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="${color}"/><circle cx="1320" cy="180" r="260" fill="#fff" opacity=".12"/><circle cx="250" cy="820" r="360" fill="#fff" opacity=".08"/><text x="120" y="390" fill="#fff" font-family="system-ui,sans-serif" font-size="180" font-weight="800">${esc(initials)}</text><text x="120" y="540" fill="#fff" font-family="system-ui,sans-serif" font-size="64" font-weight="650">${esc(agent.name)}</text><text x="120" y="620" fill="#fff" opacity=".78" font-family="system-ui,sans-serif" font-size="38">${esc(agent.department)} · Aleph featured agent</text></svg>\n`);
}

const rows = catalogAgents.map((agent) => `| ${agent.wave} | [${agent.name}](agents/${agent.slug}/README.md) | ${agent.department} | ${agent.connections.map((id) => `\`${id}\``).join(", ")} | ${agent.trigger} | ${agent.setupEffort} |`).join("\n");
await write(join(root, "CATALOG.md"), `# Featured agents catalog\n\nThis repository contains five established showcase/operational agents plus the 50 clone-ready business agents below. New catalog agents use chat and scheduled polling; they do not claim real-time connected-app triggers.\n\n## Safety contract\n\nAll generated business agents may read, research, classify, and draft automatically. Scheduled runs are read-only. Consequential writes require an exact persisted preview and explicit confirmation in a later user-authored chat turn.\n\n## Business catalog\n\n| Wave | Agent | Department | Required Connections | Trigger | Setup |\n|---:|---|---|---|---|---|\n${rows}\n\n## Established agents\n\n- [Aleph CMO](agents/aleph-cmo/README.md)\n- [Long-Term Stock Finder](agents/long-term-stock-finder/README.md)\n- [Production FinOps](agents/production-finops/README.md)\n- [Social Media Posts Scout](agents/x-engagement-scout/README.md)\n- [Weather](agents/weather/README.md)\n\n## Bundle contract\n\nEvery business catalog folder is standalone and includes catalog metadata, a cover asset, runtime instructions, Connections, schedules, lifecycle hooks, deterministic scripts, and an Agent Skill. Run \`pnpm generate\` after editing \`catalog/agents.mjs\`, then \`pnpm quality\`.\n\nConnected-app event triggers are a separate Aleph platform initiative. Until that ships, descriptions and schedules must say “scheduled polling” or “on demand,” never “real time.”\n`);

console.log(`Generated ${catalogAgents.length} catalog agents.`);
